global:
    scrape_interval: 5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: "acp-node1"
      static_configs:
          - targets: ["node1:9090"]
            labels:
                node: "node1"

    - job_name: "acp-node2"
      static_configs:
          - targets: ["node2:9090"]
            labels:
                node: "node2"

    - job_name: "acp-node3"
      static_configs:
          - targets: ["node3:9090"]
            labels:
                node: "node3"
